name: netbird-connect connection test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  connection-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Netbird Action
        uses: ./
        with:
          setup-key: ${{ secrets.NB_SETUP_KEY }}

      - name: Check for connection status
        run: |
          set -x
          netbird status